/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Health */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Commit Import
     * @description Parse a statement PDF and add it to the ledger. The PDF itself is not kept.
     */
    post: operations["commitImport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/positions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Positions */
    get: operations["listPositions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/statements/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview Statement
     * @description Parse a statement PDF and return its contents. Nothing is stored.
     */
    post: operations["previewStatement"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_commitImport */
    Body_commitImport: {
      /**
       * File
       * @description CAMS/KFintech consolidated account statement
       */
      file: string;
      /**
       * Password
       * @default
       */
      password: string;
    };
    /** Body_previewStatement */
    Body_previewStatement: {
      /**
       * File
       * @description CAMS/KFintech consolidated account statement
       */
      file: string;
      /**
       * Password
       * @default
       */
      password: string;
    };
    /** Folio */
    Folio: {
      /** Amc */
      amc: string;
      /** Folio */
      folio: string;
      /** Schemes */
      schemes: components["schemas"]["Scheme"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** ImportReceipt */
    ImportReceipt: {
      /**
       * Import Id
       * Format: uuid
       */
      import_id: string;
      /** Positions */
      positions: number;
      /** Transactions */
      transactions: number;
    };
    /** ParserInfo */
    ParserInfo: {
      /**
       * Name
       * @constant
       */
      name: "casparser";
      /** Version */
      version: string;
    };
    /** PositionSummary */
    PositionSummary: {
      /** Cost Basis */
      cost_basis: string;
      /** Folio */
      folio: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Institution */
      institution: string;
      /** Scheme */
      scheme: string;
      /** Units */
      units: string;
    };
    /** Scheme */
    Scheme: {
      /** Advisor */
      advisor: string | null;
      /** Amfi */
      amfi: string | null;
      /** Close */
      close: string;
      /** Close Calculated */
      close_calculated: string;
      /** Isin */
      isin: string | null;
      /** Open */
      open: string;
      /** Rta */
      rta: string;
      /** Rta Code */
      rta_code: string;
      /** Scheme */
      scheme: string;
      /** Transactions */
      transactions: components["schemas"]["Transaction"][];
      /** Type */
      type: string | null;
      valuation: components["schemas"]["Valuation"];
    };
    /** StatementError */
    StatementError: {
      /** Code */
      code:
        | (
            | "not_a_pdf"
            | "password_required"
            | "incorrect_password"
            | "unrecognised_statement"
            | "unsupported_statement"
            | "parse_failed"
          )
        | ("file_too_large" | "already_imported" | "commit_failed");
      /** Message */
      message: string;
    };
    /** StatementPeriod */
    StatementPeriod: {
      /** From */
      from: string;
      /** To */
      to: string;
    };
    /** StatementPreview */
    StatementPreview: {
      /**
       * Cas Type
       * @enum {string}
       */
      cas_type: "DETAILED" | "SUMMARY";
      /**
       * File Type
       * @enum {string}
       */
      file_type: "CAMS" | "KFINTECH";
      /** Folios */
      folios: components["schemas"]["Folio"][];
      /** Parse Warnings */
      parse_warnings: string[];
      parser: components["schemas"]["ParserInfo"];
      statement_period: components["schemas"]["StatementPeriod"];
    };
    /** Transaction */
    Transaction: {
      /** Amount */
      amount: string | null;
      /** Balance */
      balance: string | null;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Description */
      description: string;
      /** Dividend Rate */
      dividend_rate: string | null;
      /** Nav */
      nav: string | null;
      /**
       * Type
       * @enum {string}
       */
      type:
        | "PURCHASE"
        | "PURCHASE_SIP"
        | "REDEMPTION"
        | "DIVIDEND_PAYOUT"
        | "DIVIDEND_REINVEST"
        | "SWITCH_IN"
        | "SWITCH_IN_MERGER"
        | "SWITCH_OUT"
        | "SWITCH_OUT_MERGER"
        | "STT_TAX"
        | "STAMP_DUTY_TAX"
        | "TDS_TAX"
        | "SEGREGATION"
        | "GIFT_IN"
        | "GIFT_OUT"
        | "MISC"
        | "UNKNOWN"
        | "REVERSAL";
      /** Units */
      units: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** Valuation */
    Valuation: {
      /** Cost */
      cost: string | null;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Nav */
      nav: string;
      /** Value */
      value: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  commitImport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_commitImport"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportReceipt"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
    };
  };
  listPositions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PositionSummary"][];
        };
      };
    };
  };
  previewStatement: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_previewStatement"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementPreview"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
