/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Accounts */
    get: operations["listAccounts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/goals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Goals */
    get: operations["listGoals"];
    put?: never;
    /** Post Goal */
    post: operations["createGoal"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/goals/{goal_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Put Goal */
    put: operations["updateGoal"];
    post?: never;
    /** Delete Goal Route */
    delete: operations["deleteGoal"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/goals/{goal_id}/projection": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Projection */
    get: operations["getGoalProjection"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/goals/{goal_id}/projection/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Projection History */
    get: operations["getGoalProjectionHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/goals/{goal_id}/scheduled-transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Schedules */
    get: operations["listScheduledTransactions"];
    put?: never;
    /** Post Schedule */
    post: operations["createScheduledTransaction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Health */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Commit Import
     * @description Parse a statement PDF and add it to the ledger. The PDF itself is not kept.
     */
    post: operations["commitImport"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/positions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Positions */
    get: operations["listPositions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/scheduled-transactions/{schedule_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Schedule Route */
    delete: operations["deleteScheduledTransaction"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/statements/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview Statement
     * @description Parse a statement PDF and return its contents. Nothing is stored.
     */
    post: operations["previewStatement"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccountSummary */
    AccountSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Institution */
      institution: string;
      /** Name */
      name: string;
    };
    /** Body_commitImport */
    Body_commitImport: {
      /**
       * File
       * @description CAMS/KFintech consolidated account statement
       */
      file: string;
      /**
       * Password
       * @default
       */
      password: string;
    };
    /** Body_previewStatement */
    Body_previewStatement: {
      /**
       * File
       * @description CAMS/KFintech consolidated account statement
       */
      file: string;
      /**
       * Password
       * @default
       */
      password: string;
    };
    /** Folio */
    Folio: {
      /** Amc */
      amc: string;
      /** Folio */
      folio: string;
      /** Schemes */
      schemes: components["schemas"]["Scheme"][];
    };
    /** GoalError */
    GoalError: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | "goal_not_found"
        | "unknown_accounts"
        | "unknown_position"
        | "schedule_not_found"
        | "invalid_schedule";
      /** Message */
      message: string;
    };
    /** GoalSummary */
    GoalSummary: {
      /** Account Ids */
      account_ids: string[];
      /** Cagr Rate */
      cagr_rate: string | null;
      /** Current Value */
      current_value: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Percent Funded */
      percent_funded: string;
      /** Projection Strategy */
      projection_strategy: string | null;
      /** Target Amount */
      target_amount: string;
      /**
       * Target Date
       * Format: date
       */
      target_date: string;
      /** Trailing Window Years */
      trailing_window_years: number | null;
    };
    /**
     * GoalWrite
     * @description What the browser sends to create or edit a Goal.
     */
    GoalWrite: {
      /** Account Ids */
      account_ids?: string[];
      /** Cagr Rate */
      cagr_rate?: number | string | null;
      /** Name */
      name: string;
      /** Projection Strategy */
      projection_strategy?: ("cagr" | "trailing_window") | null;
      /** Target Amount */
      target_amount: number | string;
      /**
       * Target Date
       * Format: date
       */
      target_date: string;
      /** Trailing Window Years */
      trailing_window_years?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** HistoryPointView */
    HistoryPointView: {
      /**
       * On
       * Format: date
       */
      on: string;
      /** Projected Value */
      projected_value: string;
    };
    /** ImportReceipt */
    ImportReceipt: {
      /**
       * Import Id
       * Format: uuid
       */
      import_id: string;
      /** Positions */
      positions: number;
      /** Transactions */
      transactions: number;
    };
    /** ParserInfo */
    ParserInfo: {
      /**
       * Name
       * @constant
       */
      name: "casparser";
      /** Version */
      version: string;
    };
    /** PositionOption */
    PositionOption: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /** PositionSummary */
    PositionSummary: {
      /** Cost Basis */
      cost_basis: string;
      /** Folio */
      folio: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Institution */
      institution: string;
      /** Scheme */
      scheme: string;
      /** Units */
      units: string;
    };
    /** ProjectionHistoryView */
    ProjectionHistoryView: {
      /**
       * Goal Id
       * Format: uuid
       */
      goal_id: string;
      /** Points */
      points: components["schemas"]["HistoryPointView"][];
    };
    /** ProjectionView */
    ProjectionView: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Current Value */
      current_value: string;
      /** Gap */
      gap: string;
      /**
       * Goal Id
       * Format: uuid
       */
      goal_id: string;
      /** Projected Value */
      projected_value: string;
      /** Rate */
      rate: string | null;
      /** Status */
      status: string;
      /** Strategy */
      strategy: string | null;
      /** Target Amount */
      target_amount: string;
      /**
       * Target Date
       * Format: date
       */
      target_date: string;
      /** Trajectory */
      trajectory: components["schemas"]["TrajectoryPointView"][];
    };
    /** ScheduleBoard */
    ScheduleBoard: {
      /** Positions */
      positions: components["schemas"]["PositionOption"][];
      /** Schedules */
      schedules: components["schemas"]["ScheduleView"][];
    };
    /** ScheduleView */
    ScheduleView: {
      /** Amount */
      amount: string;
      /** Description */
      description: string;
      /** Direction */
      direction: string;
      /** End Date */
      end_date: string | null;
      /** Escalation Rate */
      escalation_rate: string;
      /** Frequency */
      frequency: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Position Id
       * Format: uuid
       */
      position_id: string;
      /** Position Name */
      position_name: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
    };
    /** ScheduleWrite */
    ScheduleWrite: {
      /** Amount */
      amount: number | string;
      /** Description */
      description: string;
      /** Direction */
      direction: string;
      /** End Date */
      end_date?: string | null;
      /**
       * Escalation Rate
       * @default 0
       */
      escalation_rate: number | string;
      /** Frequency */
      frequency: string;
      /**
       * Position Id
       * Format: uuid
       */
      position_id: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
    };
    /** Scheme */
    Scheme: {
      /** Advisor */
      advisor: string | null;
      /** Amfi */
      amfi: string | null;
      /** Close */
      close: string;
      /** Close Calculated */
      close_calculated: string;
      /** Isin */
      isin: string | null;
      /** Open */
      open: string;
      /** Rta */
      rta: string;
      /** Rta Code */
      rta_code: string;
      /** Scheme */
      scheme: string;
      /** Transactions */
      transactions: components["schemas"]["Transaction"][];
      /** Type */
      type: string | null;
      valuation: components["schemas"]["Valuation"];
    };
    /** StatementError */
    StatementError: {
      /** Code */
      code:
        | (
            | "not_a_pdf"
            | "password_required"
            | "incorrect_password"
            | "unrecognised_statement"
            | "unsupported_statement"
            | "parse_failed"
          )
        | ("file_too_large" | "already_imported" | "commit_failed");
      /** Message */
      message: string;
    };
    /** StatementPeriod */
    StatementPeriod: {
      /** From */
      from: string;
      /** To */
      to: string;
    };
    /** StatementPreview */
    StatementPreview: {
      /**
       * Cas Type
       * @enum {string}
       */
      cas_type: "DETAILED" | "SUMMARY";
      /**
       * File Type
       * @enum {string}
       */
      file_type: "CAMS" | "KFINTECH";
      /** Folios */
      folios: components["schemas"]["Folio"][];
      /** Parse Warnings */
      parse_warnings: string[];
      parser: components["schemas"]["ParserInfo"];
      statement_period: components["schemas"]["StatementPeriod"];
    };
    /** TrajectoryPointView */
    TrajectoryPointView: {
      /**
       * On
       * Format: date
       */
      on: string;
      /** Value */
      value: string;
    };
    /** Transaction */
    Transaction: {
      /** Amount */
      amount: string | null;
      /** Balance */
      balance: string | null;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Description */
      description: string;
      /** Dividend Rate */
      dividend_rate: string | null;
      /** Nav */
      nav: string | null;
      /**
       * Type
       * @enum {string}
       */
      type:
        | "PURCHASE"
        | "PURCHASE_SIP"
        | "REDEMPTION"
        | "DIVIDEND_PAYOUT"
        | "DIVIDEND_REINVEST"
        | "SWITCH_IN"
        | "SWITCH_IN_MERGER"
        | "SWITCH_OUT"
        | "SWITCH_OUT_MERGER"
        | "STT_TAX"
        | "STAMP_DUTY_TAX"
        | "TDS_TAX"
        | "SEGREGATION"
        | "GIFT_IN"
        | "GIFT_OUT"
        | "MISC"
        | "UNKNOWN"
        | "REVERSAL";
      /** Units */
      units: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** Valuation */
    Valuation: {
      /** Cost */
      cost: string | null;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Nav */
      nav: string;
      /** Value */
      value: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listAccounts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountSummary"][];
        };
      };
    };
  };
  listGoals: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalSummary"][];
        };
      };
    };
  };
  createGoal: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoalWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  updateGoal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoalWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  deleteGoal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  getGoalProjection: {
    parameters: {
      query?: {
        as_of?: string | null;
      };
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectionView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  getGoalProjectionHistory: {
    parameters: {
      query?: {
        as_of?: string | null;
      };
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectionHistoryView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  listScheduledTransactions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScheduleBoard"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  createScheduledTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduleWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScheduleView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  commitImport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_commitImport"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportReceipt"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
    };
  };
  listPositions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PositionSummary"][];
        };
      };
    };
  };
  deleteScheduledTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        schedule_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoalError"];
        };
      };
    };
  };
  previewStatement: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_previewStatement"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementPreview"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatementError"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
