class ParserException(Exception): ...  # noqa: N818  # upstream name
class HeaderParseError(ParserException): ...
class CASParseError(ParserException): ...
class IncorrectPasswordError(CASParseError): ...
class CASIntegrityError(ParserException): ...
class IncompleteCASError(ParserException): ...
